### ISSUE TITLE
HTTP Authentication

### ISSUE THREAD

**Issue by wizardlevel9** [botherder/kraken#10]
Is it possible to add authentication (username and password) to the api requests?

Use case - Agent registers with the Web UI server, but I have enabled .htpasswd to prevent everyone from viewing the data. As such the agent is not able to register. If I remove the .htpasswd then all the data is visible to everyone without authentication.

I believe that this enhancement could be accomplished by modifiying the api.go file using resty.User and altering the SetBody.

This enhancement would be very welcome.

Thankyou.

**Comment by botherder** [comment]
Sorry, but I currently do not have the time to do any development on this.
FWIW, you can have htpasswd and just set an exclusion to /api/.
