### ISSUE TITLE
Server installation instructions lack details of how to create DB

### ISSUE THREAD

**Issue by hw8665** [botherder/kraken#4]
It might be obvious to an experienced Django dev but I can't work out how to properly populate the database for the server component.

I created a kraken database in MySQL and the user + password to go with it (and updated the relevant parts of .env accordingly) so 'manage.py dbshell' works to connect correctly. I ran 'manage.py migrate' and 'manage.py createsuperuser' so I can log into the admin web UI but the DB lacks the hosts, detections, downloads or heartbeat tables so the hosts, detections and api end-points don't work

Would it be possible to add to the Web Interface instructions a HOWTO on creating the DB tables correctly?

**Comment by botherder** [comment]
That bit of documentation is lacking, true.
This should work:
```
$ python3 manage.py makemigrations autoruns detections downloads hosts
$ python3 manage.py migrate
```
