### ISSUE TITLE
Example of the config.yml

### ISSUE THREAD

**Issue by wizardlevel9** [botherder/kraken#9]
Can you please an example of what can be added to the config.yml?

I can see that the base_domain is one setting, but from the code, I can see that there are other variables as well.
Can any other variables be set within this file?

**Comment by botherder** [comment]
```
python3 manage.py --help                                                                                                                                   ✘ 130 

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser
```

**Comment by botherder** [comment]
https://kraken.gitbook.io/user-guide/how-to-use
That's the only parameter required.
